fun main()
{
    println("Enter Student's  Enrollment No.:")
    var enrollment = readLine()
    println("Enter Student's Name:")
    var name = readLine()
    println(" Enter Student's Branch:")
    var branch= readLine()
    println("Enter Student's Class:")
    var classes= readLine()
    println("Enter Student's Batch:")
    var batch= readLine()
    println("Enter Student's Collage Name:")
    var collagename = readLine()
    println("Enter Student's University Name:")
    var universityname= readLine()
    println("Enter Student's Age:")
    var age= readLine()
    println("********************************************************************")
    println("Student's  Enrollment No.:$enrollment")
    println("Student's Name:$name")
    println("Student's Branch:$branch")
    println("Student's Class:$classes")
    println("Student's Batch:$batch")
    println("Student's Collage Name:$collagename")
    println("Student's University Name:$universityname")
    println("Student's Age:$age")
}
